version: '3.6'
services:

  postgres:
    image: postgres
    expose:
      - 5432
    ports:
      - 15433:5432
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
